'use client';

import React, { useState, useEffect } from 'react';
import { Card } from '@/components/common/Card';
import { Button } from '@/components/common/Button';
import { Input } from '@/components/common/Input';
import { KeyRound, ShieldCheck, Copy, CheckCircle2, AlertTriangle, QrCode, XCircle } from 'lucide-react';
import { useAuth } from '@/lib/auth-context';
import { api } from '@/lib/api';

export default function TotpEnrolmentPage() {
  const { user } = useAuth();
  const [enrolled, setEnrolled] = useState(user?.totp_enrolled || false);
  const [step, setStep] = useState<1 | 2 | 3>(user?.totp_enrolled ? 3 : 1);
  const [secret, setSecret] = useState('JBSWY3DPEHPK3PXP');
  const [otpauthUrl, setOtpauthUrl] = useState('');
  const [verificationCode, setVerificationCode] = useState('');
  const [loading, setLoading] = useState(false);
  const [verifyError, setVerifyError] = useState<string | null>(null);
  const [copiedCodes, setCopiedCodes] = useState(false);

  const backupCodes = [
    '4821-9930',
    '7712-4019',
    '8832-1102',
    '9901-3324',
    '1245-8821',
    '6632-9012',
    '3312-7741',
    '5521-8890',
  ];

  useEffect(() => {
    async function loadSetup() {
      try {
        const data = await api.setupTotp();
        if (data.secret) setSecret(data.secret);
        if (data.otpauth_url) setOtpauthUrl(data.otpauth_url);
      } catch (err) {
        console.error('Failed to setup TOTP', err);
      }
    }
    if (!user?.totp_enrolled) {
      loadSetup();
    }
  }, [user]);

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    if (verificationCode.length !== 6) return;
    setLoading(true);
    setVerifyError(null);
    try {
      await api.verifyTotp(verificationCode);
      setEnrolled(true);
      setStep(3);
    } catch (err: any) {
      setVerifyError(err.message || 'Invalid verification code. Please check your authenticator app.');
    } finally {
      setLoading(false);
    }
  };

  const handleCopyCodes = () => {
    navigator.clipboard.writeText(backupCodes.join('\n'));
    setCopiedCodes(true);
    setTimeout(() => setCopiedCodes(false), 2000);
  };

  return (
    <div className="w-full max-w-xl mx-auto space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-on-surface">Two-Factor Authentication (TOTP)</h1>
        <p className="text-xs text-on-surface-variant">
          Step-up authentication for high-value transfers and sensitive account actions
        </p>
      </div>

      <Card className="p-6 space-y-6">
        {step === 1 && (
          <div className="space-y-5">
            <div className="flex items-center gap-3 pb-3 border-b border-outline-variant">
              <div className="w-10 h-10 rounded-lg bg-primary-fixed text-primary flex items-center justify-center">
                <KeyRound className="w-5 h-5" />
              </div>
              <div>
                <h2 className="text-base font-bold text-on-surface">Set up Authenticator App</h2>
                <p className="text-xs text-on-surface-variant">
                  Use Google Authenticator, Authy, or 1Password to scan this code
                </p>
              </div>
            </div>

            {/* Simulated QR Code Canvas */}
            <div className="p-6 rounded-lg bg-surface-container-low border border-outline-variant flex flex-col items-center justify-center space-y-3">
              <div className="w-44 h-44 bg-white p-3 rounded-md border border-outline-variant flex flex-col items-center justify-center shadow-xs">
                <QrCode className="w-32 h-32 text-slate-800" />
                <span className="text-[10px] font-mono text-outline font-semibold">PSTUPay TOTP</span>
              </div>

              <div className="text-center space-y-1">
                <span className="text-[11px] text-outline uppercase font-bold">Manual Entry Secret Key</span>
                <p className="font-mono text-xs font-bold text-primary bg-surface-container px-3 py-1 rounded">
                  {secret}
                </p>
              </div>
            </div>

            <Button variant="primary" size="lg" onClick={() => setStep(2)} className="w-full font-bold">
              Next: Verify Code
            </Button>
          </div>
        )}

        {step === 2 && (
          <form onSubmit={handleVerify} className="space-y-5">
            <h2 className="text-base font-bold text-on-surface pb-2 border-b border-outline-variant">
              Confirm 6-Digit Code
            </h2>
            <p className="text-xs text-on-surface-variant">
              Enter the 6-digit code currently generated by your authenticator app.
            </p>

            {verifyError && (
              <div className="p-3 rounded bg-red-50 border border-red-200 text-red-900 text-xs flex items-center gap-2">
                <XCircle className="w-4 h-4 text-red-600 shrink-0" />
                <span>{verifyError}</span>
              </div>
            )}

            <Input
              label="6-Digit Verification Code"
              type="text"
              maxLength={6}
              placeholder="123456"
              value={verificationCode}
              onChange={(e) => setVerificationCode(e.target.value.replace(/\D/g, ''))}
              autoFocus
              className="text-center tracking-widest text-lg font-mono"
            />

            <div className="flex gap-2 pt-2">
              <Button type="button" variant="secondary" onClick={() => setStep(1)} className="flex-1">
                Back
              </Button>
              <Button
                type="submit"
                variant="primary"
                isLoading={loading}
                disabled={verificationCode.length !== 6}
                className="flex-1 font-bold"
              >
                Complete Enrolment
              </Button>
            </div>
          </form>
        )}

        {step === 3 && (
          <div className="space-y-5 animate-in fade-in">
            <div className="p-4 rounded-lg bg-emerald-50 border border-emerald-300 text-emerald-900 flex items-center gap-3">
              <CheckCircle2 className="w-6 h-6 text-emerald-600 shrink-0" />
              <div>
                <h3 className="font-bold text-sm">Two-Factor Authentication Enrolled</h3>
                <p className="text-xs text-emerald-800">
                  Your account is protected. High-value transfers will request TOTP confirmation.
                </p>
              </div>
            </div>

            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold text-on-surface uppercase tracking-wider">
                  Single-Use Backup Codes
                </span>
                <button
                  type="button"
                  onClick={handleCopyCodes}
                  className="text-xs font-bold text-primary flex items-center gap-1 hover:underline"
                >
                  <Copy className="w-3.5 h-3.5" />
                  <span>{copiedCodes ? 'Copied to clipboard!' : 'Copy all codes'}</span>
                </button>
              </div>

              <div className="p-3 rounded bg-amber-50 border border-amber-200 text-amber-950 text-xs flex items-center gap-2">
                <AlertTriangle className="w-4 h-4 text-amber-700 shrink-0" />
                <span>Save these backup codes now. They are displayed only once.</span>
              </div>

              <div className="grid grid-cols-2 gap-2 font-mono text-xs p-3 rounded bg-surface-container-low border border-outline-variant text-center font-bold text-on-surface">
                {backupCodes.map((code, idx) => (
                  <div key={idx} className="p-1.5 rounded bg-surface-container-lowest border border-outline-variant">
                    {code}
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </Card>
    </div>
  );
}
